/* eslint-disable import/extensions */
/* eslint-disable react/jsx-filename-extension */
/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
// eslint-disable-next-line import/no-unresolved
import HeaderComponent from '../components/HeaderComponent';
// import { Inter } from '@next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Stamps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/stamps-logo.svg" />
      </Head>
      <main className="flex flex-col h-screen">
        <HeaderComponent />

      </main>
    </>
  );
}
